apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    imagePullPolicy: IfNotPresent
    name: purple-container
  initContainers:
  - command:
    - sh
    - -c
    - sleep 20
    image: busybox:1.28
    name: warm-up-1