apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-11-30T11:56:41Z"
  labels:
    name: webapp-pod
  name: webapp-pod
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    imagePullPolicy: Always
    name: webapp
    envFrom:
    - secretRef:
        name: db-secret

kubectl create secret generic --from-file=key=source 