# 문자열로 secret 생성
#kubectl create secret generic <secret-name> --from-literal=<key>=<value>
# > kubectl create secret generic app-secret --from-literal=DB_HOST=mysql --from-literal=DB_User=root --from-literal=DB_Password=passwd

# 파일을 통해 secret
#kubectl create secret generic <secret-name> --from-file=<path-to-file>
# > kubectl create secret generic app-secret --from-file=app_secret.properties

# yaml파일로 생성
# kubectl create -f secret-data.yaml

apiVerison: v1
kind: Secret
metadata:
  name: app-Secret
data:
  DB_Host: 암호화값
  DB_User: 암호화값
  DB_Password: 암호화값


# kubectl get secret app-secret -o yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
  - name: simple-webapp-color
    image: simple-webapp-color
    ports:
      - containerPort: 8080
    volumes:
    - name: app-secret-volume
      configMap:
        name: app-secret
    #볼륨 방식은 /opt/app-secret-volume 폴더에 파일명:내용 으로 저장됨
    env:
      - name: DB_Password
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_Password
    envFrom:
      - secretRef:
          name: app-config
