apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  #csr파일
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQW9aT1JjSkh0ZEZIaVJkSm5RNEpTdUhSWmVwd0VzcUgxWG13U1BUSTBZdDM1ClJFYWpkdGhRaTZOQjZnanBBMWtEbkU5QUN2ZFY2c25ESnpBY2FPU2JJK2Q4dXhBNUpPUUI2Q2RQUkVoRWdlUVUKM0lmNTJDakdKUW5JTW1sc1RneWFVWDhrTUUvSVpSclR3QnNrWC9SNTFPRjJZR1NYcWFxWEQ4WjA3YjF2TjN6QgpJMjlpZjh1N2thdm5aZ05OYUlRdUp2Mlo2OUVJVVRYa21VK3BubmJ6QUFRZStudXRxMWhwcndrakxkN01PTXNyCjl2YVJIYmpZcDdYdTdHcExFa3NuL2lZV0tCUjgrdTVWRTRpVVhWWmxFdmZlM210YVFLcERiZmJraXBPNCs3NlkKYW0yaTNuUXlUYXpGUFNOUkN4WkdDYkMvTm5FQUEzSm5EcS9JcElLc3VRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSXkxTmNCUUlzYWp1UXVmM3hvMXdGdndReUNRT3IvRGNtU3AxVytwcTBYbi9la1lKOUJKCmtMbHhBRExjVmpiaXJGbkdwS21DbmpsRTNjNzd3eERQY3lLeUVZTE9wb2JZR3AwQ0dsWTM3cmxreFdGdW9hM3YKMGdDZUc2NDQyUTFRYWZ5WDNOZnVMRWd5MWZUSEJycnU4NFVFaEJNVGRCZnpHNm1NdWJjMFh5Q0lNY3dYNjNKegovVU1CeEdoZkVPOTNseVQvc3A5d1lTWjdjaE1obWhXaFBHQVlGeHNZWFRBK2RFdWl0b2toazkwbGMyclY5amg0Clp1NEZGS1FUa2hadDMyODhlY0pGcXlYbHpkNFFNYVhEeHpOZU9JcVVoenVpTXhQWWFYZE9CWFVNRXYyMkhNVi8KU08wVXB0dXdnQ2NhemNuUkFpdTR2Y2pWa2JKdmlIQnRFNjQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth


 #kubectl certificate approve akshay
 #kubectl certificate deny agent-smith