apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTF3NThYR0RwVkFyTlFBQ25vTGZUb3FscGZQWmk0WjE5VkN3VGJNcnlINjRmCk1vcDArTlZDNk1IaUZDUjR2TFhYTXYrOFlwN2s1Njg3clI0SEt2dWxiWTVaMWNlY0RkenZZZUUyZVJveTBNTTIKaGhJZFJVUXU1c3VvVUlyQ3NvVGZtdlRWMXdib052U01kMHRQQWxEYWxUWk5QVDN6eGJ6WVROT0c4YkdFT1JzbwpxcHhQSS9jNHpvdWRJeUxTL0MrQmhlbnpLb0lmOElDanBnNWFvL0NLVkpEOG40cXUvWUlzdGVKWVY4LzU4a2p0CmhlTXRKQzVUd0VvVkxJZ0hFU20wN0IxSzFpODJOYmxZSHZscThSa1RoUWZESGZ3MjhRSmd1WUtBQ3dVZW04OTMKUG5PN2cwMVpIMVNMZEVQTkxLUlVBcTRuVUY5YW1UMWlvQU5ySGJWQmx3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRy9DZWV0Ulc4TmUybzNreFZEN3JXeEM1RDV3dzF1VHE2c2UxVm9tU25hcXBFdTV4eVFmCkpNWUNUSnB3SlhKUFFMTHFaRHNXNGxyTFlFK29GbDVFOWg1cVVsdmtWT3BBNWFvSTJqUDA4OEJ1VlBzMG1xRVIKUlZxNVlzc2p3MG5LZXJVcnFpaFZaNGlFc1Y1YkFaZFJaK003ZGxESm1pUXJ4NzBZeHJaSEtoRmxubGZObTNBUApsQUFENHVrMTAzOTVRQXpLblRRWFdtVVBOZnBsNHF0MXZoSDFVa0kwS1hHeWpmaDM0YUxzcUF5SkJxN2pxclh5CmFkMzBmbGRzVXhzTHZTV1doL1hpNTk3RjZQM3VPR3JUb2poUWZadlBpRVVHNHJVbkhianlObUF6K0Y3UDJUTEgKa3hCNStCeS9UZWQyR3FEQmszUFRvSkQrTXAwMWZJdzY4a0k9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth

# 새로운 클라이언트의 키를 등록하는 부분, request에 csr을 넣는다.
# kubectl certificate approve {csr이름}
# kubectl certificate deny {csr이름}
# kubectl get csr {csr이름} -o yaml 으로 자세하게 csr 조회 가능
#