# 문자열로 secret 생성
#kubectl create secret generic <secret-name> --from-literal=<key>=<value>
# > kubectl create secret generic app-secret --from-literal=DB_HOST=mysql --from-literal=DB_User=root --from-literal=DB_Password=passwd

# 파일을 통해 secret
#kubectl create secret generic <secret-name> --from-file=<path-to-file>
# > kubectl create secret generic app-config --from-file=app_secret.properties

# yaml파일로 생성
# kubectl create -f config-map.yaml

apiVerison: v1
kind: configmap
metadata:
  name: app-config
data:
  DB_Host: mysql
  DB_User: root
  DB_Password: passwd

---
apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
spec:
  containers:
  volumes:
  - name: app-config-volume
    secret:
      name: app-config
  - name: simple-webapp-color
    image: simple-webapp-color
    volumeMounts:
      - path: /etc/path
        name: app-config
#볼륨으로 붙일 경우 마운트 된 곳에 키:파일명 / 값:파일내용 으로 생성됨
    env:
      - name: DB_Password
        valueFrom:
          secretKeyRef:
            name: app-secret
            key: DB_Password
    envFrom:
      - secretKeyRef:
          name: app-config